##Loading Libraries

In [1]:
import pandas as pd
import numpy as np

##Loading Breast Cancer Dataset using Sklearn

In [4]:
from sklearn.datasets import load_breast_cancer
dataset=load_breast_cancer()

In [6]:
dataset.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [7]:
dataset.feature_names # to see all columns 

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [9]:
dataset.target_names # to get target columns that have to be predicted
#'malignant'----> Breast cancer ha (0)   __________  'benign'--> no breast cancer (1)

array(['malignant', 'benign'], dtype='<U9')

In [10]:
# in 3 to 4 above cell u ran dataset.data giving a dictionary form data... and ML algo needs it in DataFrame so we need to convert it into DataFrame
# Always in Support Vector Machine u need dataset converted into DataFrame weather it is Classification or Regresssion Problem.... So see below cell

In [13]:
df=pd.DataFrame(np.c_[dataset.data, dataset.target], columns=[list(dataset.feature_names)+["Target"]])

In [14]:
## SEE ABOVE CAREFULLY  SYntax is very imp i.e np.c_[]
#  np.c_ ===> combines both dataset.data and dataset.target columns --> (It seems to be some kind of horizontal concatenation)
#See Example in next cell

In [17]:
np.c_[np.array([[1,2,3,4]]), 0, 0 , np.array([[5,6,7,9]])] # see results 

array([[1, 2, 3, 4, 0, 0, 5, 6, 7, 9]])

In [18]:
#columns=[list(dataset.feature_names)+["Target"]] for this part it simply convertes the features into the columns and
# +['target'] is giving name to last column which is our target

In [ ]:
#How do I convert data from a Scikit-learn Bunch object to a Pandas DataFrame?
#SEE ANOTHER EXAMPLE  (don't Run this consider this example only)

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# save load_iris() sklearn dataset to iris
# if you'd like to check dataset type use: type(load_iris())
# if you'd like to view list of attributes use: dir(load_iris())
iris = load_iris()

# np.c_ is the numpy concatenate function
# which is used to concat iris['data'] and iris['target'] arrays 
# for pandas column argument: concat iris['feature_names'] list
# and string list (in this case one string); you can make this anything you'd like..  
# the original dataset would probably call this ['Species']
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

###Lets see the Dataset of breast_cancer

In [19]:
df.head(5) # Target column 1 means no cancer , whereas 0 means cancer

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension Target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [22]:
print(df.shape)

(569, 31)


In [23]:
X=df.iloc[:,0:-1] #all columns except last column [all rows:all columns , all rows 0 :    -1 except last column]
y=df.iloc[:,-1]# just include last one target column

In [25]:
print("Shape of X (Independent varaible) => ", X.shape)
print("Shape of Y (Dependent Varaible;)  => ", y.shape)

Shape of X (Independent varaible) =>  (569, 30)
Shape of Y (Dependent Varaible;)  =>  (569,)


In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train ,y_test=train_test_split(X, y , test_size=0.2 , random_state=51)

In [30]:
print ("Shape of X_train => ", X_train.shape)
print ("Shape of X_train => ", X_test.shape)
print ("Shape of X_train => ", y_train.shape)
print ("Shape of X_train => ", y_test.shape)

Shape of X_train =>  (455, 30)
Shape of X_train =>  (114, 30)
Shape of X_train =>  (455,)
Shape of X_train =>  (114,)


##Training Support Vector Classifier

In [31]:
from sklearn.svm import SVC

In [32]:
Classifier_rbf=SVC(kernel='rbf')
Classifier_rbf.fit(X_train, y_train)

Classifier_rbf.score(X_test, y_test)
#SEE 90% accurate a good accuracy............. let's try others as well

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9035087719298246

In [33]:
Classifier_linear=SVC(kernel='linear')
Classifier_linear.fit(X_train, y_train)

Classifier_linear.score(X_test,y_test)
#Even more good accuracy :) ................. let's try Polynomail kernel

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9385964912280702

In [34]:
Classifier_poly=SVC(kernel='poly', degree=2)
Classifier_poly.fit(X_train, y_train)

Classifier_poly.score(X_test, y_test)
#good but 'linear has more good accuracy' even degree is 3 now 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9035087719298246

In [35]:
Classifier_poly=SVC(kernel='poly', degree=3)
Classifier_poly.fit(X_train, y_train)

Classifier_poly.score(X_test, y_test)
#good but 'linear has more good accuracy' even degree is 3 now 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9035087719298246

In [ ]:
## WE haven't done Feature scaling and let's see these all kernels after Feature Scalling

#After Feature Scalling

In [36]:
from sklearn.preprocessing import StandardScaler


In [37]:
sc=StandardScaler()

In [38]:
sc.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


StandardScaler()

In [40]:
X_train_Feature_scaled=sc.transform(X_train)
X_test_Feature_scaled=sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


##Training After Feature Scalling now 

In [42]:
Classifier_rbf1=SVC(kernel='rbf')
Classifier_rbf1.fit(X_train_Feature_scaled, y_train) #X_train_Feature_scaled is now passed instead of X_train

Classifier_rbf1.score(X_test_Feature_scaled, y_test) #X_test_Feature_scaled is now passed instead of X_test
#SEE after Feature Scaling accuracy improved by 4% --> (94%) accurate a good accuracy............. let's try others as well

0.9473684210526315

In [44]:
Classifier_linear1=SVC(kernel='linear')
Classifier_linear1.fit(X_train_Feature_scaled, y_train)#X_train_Feature_scaled is now passed instead of X_train

Classifier_linear1.score(X_test_Feature_scaled,y_test)  #X_test_Feature_scaled is now passed instead of X_test
#Even more good accuracy SEE after Feature Scaling accuracy improved by 1% --> (93%) :) ................. Same as rbf kernel above cell

0.9473684210526315

In [45]:
Classifier_poly1=SVC(kernel='poly', degree=2)
Classifier_poly1.fit(X_train_Feature_scaled, y_train)#X_train_Feature_scaled is now passed instead of X_train

Classifier_poly1.score(X_test_Feature_scaled, y_test)#X_test_Feature_scaled is now passed instead of X_test
#See after scalling not good accuracy after scalling ------So as kernel rbf and 'linear' have given same accuracy use any of above for prediction 

0.7982456140350878

#Predict cancer with featured transformed 'rbf' kernel

In [51]:
# Suppose this data comes (with 30 feature values) for a new patient and u have to see weather Patient has cancer or not 
#'malignant'----> Breast cancer ha (0)   __________  'benign'--> no breast cancer (1)
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [55]:
#but this input is in list form and also not featured scaled ----- Keep in mind these things (industral needs) -----so 
scaled_arrayed_new_data=sc.transform(np.array([patient1]))
print(scaled_arrayed_new_data)

[[ 1.08251028 -2.12451742  1.25006067  0.97254965  1.46781549  3.16232325
   2.55846034  2.48486634  2.09624644  2.08993201  2.35827558 -0.60226207
   2.66093534  2.33053219 -0.23730082  1.19245085  0.62261841  0.57360654
   1.02616522  0.80379075  1.88782615 -1.39038516  2.29703524  2.00795595
   1.24539341  2.53896053  2.0206957   2.25059294  2.65132987  1.82722173]]


In [57]:
pred=Classifier_rbf1.predict(scaled_arrayed_new_data)
pred #means pateint has cancer

array([0.])

In [60]:
if pred[0]==0: # see this it means when first index of pred is 0 then it is eqaul to 0 ---Because (see next cell)
  print("Malignant--> Patient has a Breast Cancer (0)")
else:
    print("Benign---> Patient has no Breast Cancer(1)")

Malignant--> Patient has a Breast Cancer (0)


In [61]:
dataset.target_names 
#index 0=Malignant ........1 =Benign

array(['malignant', 'benign'], dtype='<U9')